README.md

I'd like to add Klipfolio to the list. Full transparency... I work for Klipfolio.

adding Klipfolio

---

README.md

fixes some broken URLs and marks services as EOL where possible

typos and updates

---

README.md

Removed Calq

---

README.md

Removed duplicate klout.com link

Removed Duplicate URl

---

README.md

Removed Klout

---

README.md

Metabase is an opensource analytics/BI tool
disclaimer: I'm one of the core contributors

Add Metabase to General

---

README.md

Added Adobe Analytics into General analytics section.

Added Adobe Analytics into General analytics

---

README.md

Metabase can drop in and plug into a lot of different database types. It has a low learning curve for non technical users and great user access permissions control. It is also a handy way for someone to learn SQL from a GUI first approach.

Added Metabase to the Dashboards section

---

README.md

Disclaimer: I'm the author of GoatCounter.

Add GoatCounter

---

README.md

Hey @onurakpolat 
I've found two dead links in the heatmap section. Here is fix for this.
Cheers!

Removing two dead projects from heatmap section

---

README.md

Noticed a small error and I thought of submitting a PR to adjust it 🤷‍♂️

Update README spelling error

---

README.md

Hey @onurakpolat 
just a small fix for a link - it missed a /
Cheers!

Fixing onliquid.com link

---

README.md

disclaimer: I am one of the people that built PostHog, it should fit in with the list nicely I hope! :)

Added PostHog

---

README.md

Disclaimer: I work on Plausible.

Add Plausible Analytics

---

README.md

This PR adds [Shynet](https://github.com/milesmcc/shynet), an open source analytics tool I've been working on. I added it in alphabetical order to the "Privacy Focused Analytics" section; hopefully that's the right place for it!

Add Shynet

---

README.md

awesome-selfhosted-merge: block 1

---

README.md

awesome-selfhosted-merge: block 2

---

README.md

awesome-selfhosted-merge: block 3

---

README.md

awesome-selfhosted-merge: block 4

---

README.md

awesome-selfhosted-merge: block 5

---

README.md

awesome-selfhosted-merge: block 6

---

README.md

Added Kindmetrics.
Disclaimer: I am the founder of Kindmetrics

Added Kindmetrics

---

README.md

Updated the RudderStack info to reflect it's updated name, description, links, and license.

Updated RudderStack info.

---

README.md

http://www.opentracker.net/ - no longer working

http://www.opentracker.net/

---

README.md

https://chartbeat.com/ - no longer working

https://chartbeat.com/

---

README.md

http://sitemeter.com/ - no longer working

http://sitemeter.com/

---

README.md

Please, include EDA in your awesome list. 
We have developed EDA with a special focus on business users and ease of use

Enterprise Data Analytics ( EDA )

---

README.md

Add Panelbear

---

README.md

- fixes https://github.com/onurakpolat/awesome-analytics/issues/94
- https://github.com/onurakpolat/awesome-analytics/issues/93
ping @koconder @jtagcat

mark non-self-hostable software as SaaS, non-Free software with ©

---

README.md

In https://github.com/onurakpolat/awesome-analytics/pull/109 I missed some items that should have been tagged with `©` `SaaS`
/cc @onurakpolat @koconder

add missing `©` `SaaS` tags

---

README.md

Related https://github.com/onurakpolat/awesome-analytics/issues/112

Remove some duplicates

---

README.md

Update README.md (gitspo multiple entries)

---

README.md

I work at PostHog and just wanted to mention we've added some cool, big new features lately!
We can also be privacy focused through self-hosting, for what it's worth. :)

Adding some features to PostHog

---

README.md

Hatica is an Engineering (Git) Analytics platform to help boost developer productivity

Adding Hatica to Developer analytics
